-- ============================================================
--  RESTAURANTE UNIVERSITARIO -- CRIACAO DAS TABELAS
-- ============================================================


-- CRIA TABELA EMPRESA
CREATE TABLE EMPRESA(
ID NUMBER(10),
CONSTRAINT PK_EMPRESA PRIMARY KEY (ID)
);


-- CRIA TABELA UNIVERSIDADE
CREATE TABLE UNIVERSIDADE(
SIGLA  VARCHAR(10),
CAMPUS VARCHAR(100) CONSTRAINT NN_UNIV_CAMPUS NOT NULL,
CONSTRAINT PK_UNIVERSIDADE PRIMARY KEY (SIGLA)
);


-- CRIA TABELA ALUNO
CREATE TABLE ALUNO(
CPF       VARCHAR(11),
MATRICULA VARCHAR(20)    CONSTRAINT NN_ALU_MAT  NOT NULL,
NOME      VARCHAR(100)   CONSTRAINT NN_ALU_NOME NOT NULL,
SALDO     NUMBER(10, 2)  DEFAULT 0 NOT NULL,
CONSTRAINT PK_ALUNO    PRIMARY KEY (CPF),
CONSTRAINT AK_ALU_MAT  UNIQUE (MATRICULA),
CONSTRAINT CHK_ALU_SALDO CHECK (SALDO >= 0)
);


-- CRIA TABELA RESTAURANTE
CREATE TABLE RESTAURANTE(
ID_RESTAURANTE NUMBER(10),
FK_SIGLA       VARCHAR(10)  NOT NULL,
FK_ID_EMPRESA  NUMBER(10)   NOT NULL,
CONSTRAINT PK_RESTAURANTE PRIMARY KEY (ID_RESTAURANTE, FK_SIGLA),
CONSTRAINT FK_REST_UNIV   FOREIGN KEY (FK_SIGLA)      REFERENCES UNIVERSIDADE (SIGLA),
CONSTRAINT FK_REST_EMP    FOREIGN KEY (FK_ID_EMPRESA)  REFERENCES EMPRESA (ID)
);


-- CRIA TABELA FUNCIONARIO
CREATE TABLE FUNCIONARIO(
CPF               VARCHAR(11),
FK_CPF_CHEFE      VARCHAR(11),
FK_ID_RESTAURANTE NUMBER(10),
FK_SIGLA          VARCHAR(10),
CONSTRAINT PK_FUNCIONARIO  PRIMARY KEY (CPF),
CONSTRAINT FK_FUNC_CHEFE   FOREIGN KEY (FK_CPF_CHEFE)                    REFERENCES FUNCIONARIO (CPF),
CONSTRAINT FK_FUNC_REST    FOREIGN KEY (FK_ID_RESTAURANTE, FK_SIGLA)     REFERENCES RESTAURANTE (ID_RESTAURANTE, FK_SIGLA)
);


-- CRIA TABELA PAGAMENTO
-- TRIGGER TRG_SALDO_PAGAMENTO SOMA O VALOR AO SALDO DO ALUNO APOS INSERT
CREATE TABLE PAGAMENTO(
NUM_NOTA_FISCAL   VARCHAR(30),
VALOR             NUMBER(10, 2)  NOT NULL,
DATA              DATE           NOT NULL,
FK_ID_RESTAURANTE NUMBER(10)    NOT NULL,
FK_SIGLA          VARCHAR(10)   NOT NULL,
FK_CPF_ALUNO      VARCHAR(11)   NOT NULL,
CONSTRAINT PK_PAGAMENTO  PRIMARY KEY (NUM_NOTA_FISCAL),
CONSTRAINT CHK_PAG_VALOR CHECK (VALOR > 0),
CONSTRAINT FK_PAG_REST   FOREIGN KEY (FK_ID_RESTAURANTE, FK_SIGLA) REFERENCES RESTAURANTE (ID_RESTAURANTE, FK_SIGLA),
CONSTRAINT FK_PAG_ALU    FOREIGN KEY (FK_CPF_ALUNO)                REFERENCES ALUNO (CPF)
);


-- CRIA TABELA SETOR
CREATE TABLE SETOR(
COD  NUMBER(10),
NOME VARCHAR(100) CONSTRAINT NN_SETOR_NOME NOT NULL,
CONSTRAINT PK_SETOR PRIMARY KEY (COD)
);


-- CRIA TABELA EQUIPAMENTOS
CREATE TABLE EQUIPAMENTOS(
FK_COD_SETOR NUMBER(10),
EQUIPAMENTOS VARCHAR(100),
CONSTRAINT PK_EQUIPAMENTOS  PRIMARY KEY (FK_COD_SETOR, EQUIPAMENTOS),
CONSTRAINT FK_EQUIP_SETOR   FOREIGN KEY (FK_COD_SETOR) REFERENCES SETOR (COD)
);


-- CRIA TABELA ZELADOR
-- FK_COD_SETOR NULLABLE: PARTICIPACAO PARCIAL NO RELACIONAMENTO LIMPA
CREATE TABLE ZELADOR(
CPF          VARCHAR(11),
FK_COD_SETOR NUMBER(10),
CONSTRAINT PK_ZELADOR   PRIMARY KEY (CPF),
CONSTRAINT FK_ZEL_FUNC  FOREIGN KEY (CPF)          REFERENCES FUNCIONARIO (CPF),
CONSTRAINT FK_ZEL_SETOR FOREIGN KEY (FK_COD_SETOR) REFERENCES SETOR (COD)
);


-- CRIA TABELA COZINHEIRO
CREATE TABLE COZINHEIRO(
CPF           VARCHAR(11),
ESPECIALIDADE VARCHAR(100) CONSTRAINT NN_COZ_ESP NOT NULL,
CONSTRAINT PK_COZINHEIRO PRIMARY KEY (CPF),
CONSTRAINT FK_COZ_FUNC   FOREIGN KEY (CPF) REFERENCES FUNCIONARIO (CPF)
);


-- CRIA TABELA REFEICAO
CREATE TABLE REFEICAO(
COD       NUMBER(10),
BEBIDA    VARCHAR(100),
PROTEINA  VARCHAR(100),
GUARNICAO VARCHAR(100),
ENTRADA   VARCHAR(100),
TIPO      VARCHAR(50)   CONSTRAINT NN_REF_TIPO  NOT NULL,
VALOR     NUMBER(10, 2) CONSTRAINT NN_REF_VALOR NOT NULL,
CONSTRAINT PK_REFEICAO    PRIMARY KEY (COD),
CONSTRAINT CHK_REF_VALOR  CHECK (VALOR > 0)
);


-- CRIA TABELA PREPARA
CREATE TABLE PREPARA(
FK_CPF_COZINHEIRO VARCHAR(11),
FK_COD_REFEICAO   NUMBER(10),
CONSTRAINT PK_PREPARA   PRIMARY KEY (FK_CPF_COZINHEIRO, FK_COD_REFEICAO),
CONSTRAINT FK_PREP_COZ  FOREIGN KEY (FK_CPF_COZINHEIRO) REFERENCES COZINHEIRO (CPF),
CONSTRAINT FK_PREP_REF  FOREIGN KEY (FK_COD_REFEICAO)   REFERENCES REFEICAO (COD)
);


-- CRIA TABELA BRINDE
CREATE TABLE BRINDE(
COD  NUMBER(10),
NOME VARCHAR(100) CONSTRAINT NN_BRIN_NOME NOT NULL,
CONSTRAINT PK_BRINDE PRIMARY KEY (COD)
);


-- CRIA TABELA SERVE
-- FK_COD_BRINDE NULLABLE: BRINDE E OPCIONAL POR ATENDIMENTO
-- TRIGGER TRG_SALDO_SERVE SUBTRAI VALOR DA REFEICAO DO SALDO DO ALUNO APOS INSERT
CREATE TABLE SERVE(
FK_ID_RESTAURANTE NUMBER(10),
FK_SIGLA          VARCHAR(10),
FK_COD_REFEICAO   NUMBER(10),
FK_CPF_ALUNO      VARCHAR(11),
DATA              DATE,
FK_COD_BRINDE     NUMBER(10),
CONSTRAINT PK_SERVE       PRIMARY KEY (FK_ID_RESTAURANTE, FK_SIGLA, FK_COD_REFEICAO, FK_CPF_ALUNO, DATA),
CONSTRAINT FK_SERVE_REST  FOREIGN KEY (FK_ID_RESTAURANTE, FK_SIGLA) REFERENCES RESTAURANTE (ID_RESTAURANTE, FK_SIGLA),
CONSTRAINT FK_SERVE_REF   FOREIGN KEY (FK_COD_REFEICAO)             REFERENCES REFEICAO (COD),
CONSTRAINT FK_SERVE_ALU   FOREIGN KEY (FK_CPF_ALUNO)                REFERENCES ALUNO (CPF),
CONSTRAINT FK_SERVE_BRIN  FOREIGN KEY (FK_COD_BRINDE)               REFERENCES BRINDE (COD)
);


-- ============================================================
--  TRIGGERS -- MANUTENCAO DO SALDO DO ALUNO
-- ============================================================


-- TRIGGER: SOMA AO SALDO QUANDO ALUNO EFETUA PAGAMENTO
CREATE OR REPLACE TRIGGER TRG_SALDO_PAGAMENTO
AFTER INSERT ON PAGAMENTO
FOR EACH ROW
BEGIN
    UPDATE ALUNO
    SET    SALDO = SALDO + :NEW.VALOR
    WHERE  CPF   = :NEW.FK_CPF_ALUNO;
END;
/


-- TRIGGER: SUBTRAI DO SALDO QUANDO REFEICAO E SERVIDA AO ALUNO
CREATE OR REPLACE TRIGGER TRG_SALDO_SERVE
AFTER INSERT ON SERVE
FOR EACH ROW
DECLARE
    V_VALOR NUMBER(10, 2);
BEGIN
    SELECT VALOR INTO V_VALOR
    FROM   REFEICAO
    WHERE  COD = :NEW.FK_COD_REFEICAO;

    UPDATE ALUNO
    SET    SALDO = SALDO - V_VALOR
    WHERE  CPF   = :NEW.FK_CPF_ALUNO;
END;
/
